#!/bin/bash

# Example usage:
# setup_pyenv.sh 3.7.3 requirements.txt


# Setup pyenv if not installed
if [[ ! -d "$HOME/.pyenv" ]]; then
    echo Installing pyenv
    git clone https://github.com/pyenv/pyenv.git ~/.pyenv
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
    echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
    echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.bashrc
else
    echo Found pyenv
fi

# Install python version if not installed
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$HOME/.pyenv/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi


if pyenv versions | grep -qF $1;then
    echo Found python$1
    pyenv global $1
else
    echo Installing python$1
    pyenv install -f $1
    pyenv global $1
fi

# Install python packages
python --version
pip install -r $2

# TODO: move this to python sftp
rm -rf .more_cores
mkdir .more_cores
cd .more_cores
